MAX_LENGTH: int = 256
LIMIT_LENGTH: int = 50

MIN_SCORE_VALUE: int = 1
MAX_SCORE_VALUE: int = 10

MAX_LENGTH_NAME: int = 150
MAX_LENGTH_EMAIL: int = 254
MAX_LENGTH_ROLE: int = 20

MIN_PAGINATION_VALUE: int = 1
MIDDLE_PAGINATION_VALUE: int = 2
MAX_PAGINATION_VALUE: int = 10

REGEX_USERNAME: str = r'^[\w.@+-]+\Z'
REGEX_SLUG_BASE_MODEL: str = r'^[-a-zA-Z0-9_]+$'
MIN_VALUE_VALIDATOR: int = 0
