# Generated by Django 3.2 on 2024-10-02 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='author_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
